name: PR Collection Labeler

on: pull_request_target

jobs:
  pr_collection_labeler:
    runs-on: ubuntu-latest
    steps:
    - name: Add collection labels
      uses: ignition-tooling/pr-collection-labeler@chapulina/debug
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
